// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpihjxfnRFw6YNE57SkOIJWOU4C99poO8',
    appId: '1:764872486060:web:3a28dddcd6aa7a8c118309',
    messagingSenderId: '764872486060',
    projectId: 'hello-d49e0',
    authDomain: 'hello-d49e0.firebaseapp.com',
    storageBucket: 'hello-d49e0.appspot.com',
    measurementId: 'G-1D88BJ329M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANP5uAr5PfnIcDVdOTd78f_TUDeg2jx2I',
    appId: '1:764872486060:android:3649fa2ee16ecbd9118309',
    messagingSenderId: '764872486060',
    projectId: 'hello-d49e0',
    storageBucket: 'hello-d49e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC57cEdjaO1OLapAUJVuMqvt_w9mzYmqUo',
    appId: '1:764872486060:ios:b3e78b018c1f7f95118309',
    messagingSenderId: '764872486060',
    projectId: 'hello-d49e0',
    storageBucket: 'hello-d49e0.appspot.com',
    iosClientId: '764872486060-vfpvfbtfjn9mki810fjcuu2q73k7nu3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC57cEdjaO1OLapAUJVuMqvt_w9mzYmqUo',
    appId: '1:764872486060:ios:b3e78b018c1f7f95118309',
    messagingSenderId: '764872486060',
    projectId: 'hello-d49e0',
    storageBucket: 'hello-d49e0.appspot.com',
    iosClientId: '764872486060-vfpvfbtfjn9mki810fjcuu2q73k7nu3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
